### ISSUE TITLE
Wrong package name at the installation instructions

### ISSUE THREAD

**Issue by FelipeIvanaga** [catppuccin/insomnia#1]
Hi.

The package name on `README.MD` at the installation instructions is `insomnia-plugin-theme-catppuccin`, but the package name of Insominia Plugin Hub is `insomnia-plugin-catppuccin`

Trying to install with `insomnia-plugin-theme-catppuccin` throws an error.

```
Error: Error invoking remote method 'installPlugin': Error: Yarn error warning insomnia-plugin-theme-catppuccin@1.0.1: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.

    at o.invoke (node:electron/js2c/renderer_init:57:526)
    at async BP._handleAddFromNpm (file:///opt/Insomnia/resources/app.asar/index.e0c63af2.js:1849:44230)
```

Installing with `insomnia-plugin-catppuccin` works fine.

**Comment by opakholis** [comment]
The issue has been fixed with the PR above, let us know if you still find something unexpected, Thanks!
