### ISSUE TITLE
Failed to install plugin

### ISSUE THREAD

**Issue by zoedsoupe** [catppuccin/insomnia#3]
Cannot install plugin neither from plugin hub or by name. My insomnia version is `2023.0.1`.

None stack trace was provided too 😕 

<img width="903" alt="Screenshot 2023-04-04 at 17 18 46" src="https://user-images.githubusercontent.com/44469426/229910858-93239bd6-a93c-4901-828a-d2fb2c12611a.png">

**Comment by opakholis** [comment]
I'm currently quite busy, but I'll try to look into it during my spare time, perhaps over the weekend.

**Comment by zoedsoupe** [comment]
no problem! 😊

**Comment by opakholis** [comment]
Hi @zoedsoupe

I'm not experiencing the issue you mentioned. Both methods work fine for me. 

Perhaps using the latest version of Insomnia might be helpful, I think.

![CleanShot 2023-04-07 at 15 43 06](https://user-images.githubusercontent.com/49778014/230576156-1cfcca8e-22a5-4614-918d-eac8efd92214.jpg)

**Comment by zoedsoupe** [comment]
Indeed... That's so strange because I was already using the latest version `v2023.1.0` 😕 

Know it worked haha
