### ISSUE TITLE
Can't install the plugin

### ISSUE THREAD

**Issue by paulomanrique** [catppuccin/insomnia#4]
When I try to install, I get this error:

```
Failed to install insomnia-plugin-catppuccin

There may be an issue with the plugin itself, as a note you can discover and install plugins from the [Plugin Hub.](https://insomnia.rest/plugins)
Additional Information
Error: Error invoking remote method 'installPlugin': Error: Yarn error {"type":"warning","data":"package.json: No license field"}

    at a.invoke (node:electron/js2c/renderer_init:2:7610)
    at async onSubmit (file:///C:/Users/Paulo/AppData/Local/insomnia/app-2023.2.0/resources/app.asar/index.db3b02b7.js:189:488)
```

**Comment by MrEnder0** [comment]
Error: Error invoking remote method 'installPlugin': Error: Yarn error {"type":"warning","data":"package.json: No license field"}

    at a.invoke (node:electron/js2c/renderer_init:2:7610)
    at async onSubmit (file:///C:/Users/Ender/AppData/Local/insomnia/app-2023.2.2/resources/app.asar/index.a9c30483.js:190:488)

**Comment by FabyoSK** [comment]
I'm unable to install it as well

**Comment by sgoudham** [comment]
Hi :wave: 
It seems like this issue affects users in other plugins too, seen in https://github.com/syl20lego/insomnia-plugin-aws-cognito-token/issues/4.
I was able to install the theme by following the workaround in the comments:

```shell
cd /path/to/your/insomnia/plugins/directory
git clone git@github.com:catppuccin/insomnia.git insomnia-plugin-catppuccin
cd insomnia-plugin-catppuccin
npm install
```

I was then able to pick my themes by going to  `Applications` -> `Preferences` -> `Themes`

![image](https://github.com/catppuccin/insomnia/assets/58985301/1ab4ad22-53f6-47fe-b8e8-70f9cba2ed1a)

I'm not sure if its documented anywhere why this happens but I'll be closing this issue as there is a workaround. I'll link to this issue in the README.md!
