### ISSUE TITLE
Credentials for NPM & Insomnia Store

### ISSUE THREAD

**Issue by sgoudham** [catppuccin/insomnia#5]
Hi :wave: @opakholis

I'm one of current owners of the Catppuccin GitHub organisation, who wasn't around for the introduction/merge of this repository. I've been going through our older repositories and saw this repository's NPM package is outside of the catppuccin NPM organisation  and there's an Insomnia Store account that has published the theme.

Could I confirm you have access both of those accounts, and if so could you please:

1. Invite me as an owner to the [NPM package](https://www.npmjs.com/package/insomnia-plugin-catppuccin), my username is [hamothy](https://www.npmjs.com/~hamothy).
2. Provide the login details of the [Insomnia Store account](https://insomnia.rest/plugins/insomnia-plugin-catppuccin), as they are now controlled by the leadership teams. Please email these credentials to core@catppuccin.com or if you are reachable via discord, please send a friend request to [hamothy](https://toolscord.com/) to chat.

If you are not the owner of these accounts, do you know who might be? 
Thanks!

**Comment by opakholis** [comment]
Hi @sgoudham, 

Yes, I am. At that time, it was only informed to transfer the Github repo. Let's also do it for the NPM package then.

**Comment by sgoudham** [comment]
Hey, 

Thanks for confirming! I wasn't sure if you could transfer packages on NPM but it looks like you can: https://docs.npmjs.com/transferring-a-package-from-a-user-account-to-another-user-account#transferring-a-package-from-a-user-account-to-another-user-account-on-the-website

I'd appreciate that, do you know if it's relatively easy to transfer this package into the catppuccin NPM organisation directly? i.e get it under `@catppuccin/insomnia-plugin-catppuccin`?

**Comment by sgoudham** [comment]
Also could I confirm that you are willing to maintain this repository going forward? 
i.e. respond to issues, merge PRs, etc.
