### ISSUE TITLE
Can't install plugin. 

### ISSUE THREAD

**Issue by GravityScriptsV2** [catppuccin/insomnia#9]
Failed to install insomnia-plugin-catppuccin. Please contact the plugin author sharing the below stack trace to help them to ensure compatibility with the latest Insomnia.
Try using the install button on [Plugin Hub.](https://insomnia.rest/plugins)
Additional Information
Error: Error invoking remote method 'installPlugin': Error: Yarn error {"type":"warning","data":"package.json: No license field"}

**Comment by sgoudham** [comment]
Hi 👋 

Please see https://github.com/catppuccin/insomnia/issues/4#issuecomment-2021736443 for a workaround, this error seems to affect other plugins too and the root cause is currently unknown.
